#+title chuggboarder-micro-blog

* Introduction
The concept here is a low-friction way to write down my thoughts, organized by date.

** Starting a blogging practice
:PROPERTIES:
  :CREATED: <2026-01-05 Mon>
  :END:
*** aims
 - maintain my practice using git and emacs even when I don't have the
   time or energy to craft a complete git commit on one of my other projects.
 - benefits of blogging as described by [[https://pages.sachachua.com/sharing/blog.html][Sacha Chua]]

*** distilled point
I had a placeholder repo here for a "landing page" without much in it.
I think my landing page ought to be tied to my professional CV on my
other account. I turned this into my personal "micro-blog"

*** discussion
The thing I want to drive here is consistency.

The long and short of it is that I am in my 30s and still dream like a
college kid.  This is probably a good thing, since you hear people
talk about having all this motivation in their 20s and then acheiving
some measure of success but losing the motivation.  I remember being
younger and feeling overwhelmed with starting a career on nothing.
How am I supposed to start with anything if I don't have experience? I
wanted to start a few wrungs up on the ladder.  Now I'm there sort of.
I'm on a ladder at least, how many wrungs up is subjective. But for
some reason the ladder isn't worth climbing and there's no easy
platform to dismount. Then I begin to feel like I've done the wrong
thing with my life and I need to go back to school or whatever.  This
is of course absurd. I am just reacting to the normal forces lots of
people encounter in their life, and I can just develop my own aims
independent of my career.  I can also develop my career independent of
my goals and other aims.  So it is fitting I maintain this space here to develop
by broader goals through the practice of writing.

I had this written up using the term "goals" but I changed it to
"aims".  I want to use this blogging practice to develop the broad
aims that one doesn't measure precisely enough to tell if you succeed
or fail. To me right now, aims are tools.  An aim has the goal to
enrich the product of the time earmarked to it. I want to be careful
here as to avoid a thing that is all too common: to talk one's self
out of success.

* topics
:PROPERTIES:
  :CREATED: <2026-01-05 Mon 19:42>
  :END:

These are topics that are supposed to fit the stated aims of the
blog. They are all things I must continue to do for the rest of my
life, but they are also things I wish to do effectively and masterfully.

** cleaning
*** wash dishes
I wash dishes almost every day.

*** fitness

** cooking

** computer work

<2026-01-10 Sat 22:14>
I want to learn Guix and scheme to manage my systems and tooling. I
want to learn p_slides, reveal.js, beamer, or some other declarative
method to create presentation slides. I think this would be a good way
to package data analysis findings.  It would be a good thing to
include in a professional portfolio for data analysis.

I have some practical supply chain analysis projects that I already
use for work that could greatly benefit from some automation and/or
some reproducibility practices. There is a cadence of formal daily and
monthly reports, and there are also ad-hoc inventory analyses that are
repeated over and over again as required. For both cases it's really
just SAP data extraction and some spreadsheet style manipulation. I
really would like to organize these into formal workflows using Emacs
Org mode tables and code blocks.  I think there is a real opportunity
to apply scientific computing practices to business domains to aid
with decision making.

** yard work

<2026-01-10 Sat 22:19>
I met with a tree guy today. My fiancee arranged the meeting. We are
planning to get married in our semi-wooded back yard that slopes down
toward a creek.  At this point we think this will necessitate the
removal of at least 1 considerably large oak tree.


* 2026-01-06 work from home
:PROPERTIES:
  :CREATED: <2026-01-06 Tue 11:11>
  :END:

i'm gonna jot down some thoughts and stream it for some reason.

- i moved some rocks earlier.
- check work email
- let Olive out
- start some laundry
- do a work report


later note <2026-01-10 Sat 21:45> -- i did not end up doing the work
report that day. I did that in the office later in the week.


